_format_version: "2.1"
_transform: true

services:
  - url: http://echo
    routes:
      - paths:
          - "/jwt"
    plugins:
      - name: kong-jwt-plugin
        config:
          jwt:
            prefix: "bce"
            claims:
              - name: "uid"
          publickey: |
            -----BEGIN PUBLIC KEY-----
            MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwr1BKvAQRnXADBjMVucJ
            I9hKC4U4H3cQQokUHQRDCnuHZTMcsVdB9NR7ucnp1qsDt716+Drz3lheyQiZhyVg
            ij3BBhfB0Oscw66hhjwwJR4EZXQ3SZb/UiPLbx8TgyOj4yru8tzoDzz8WUs7cadh
            zE4oubpfGatTVbWa08VB0eKzPQx5EYFN9okUYx/+6AIZJv38J5NHld663Sc+oUwl
            1r+faxcZhXg6kSW9zVUoR+MCAwEAAQ==
            -----END PUBLIC KEY-----

  - url: http://echo
    routes:
      - paths:
          - "/forward-auth"
    plugins:
      - name: kong-forward-auth-plugin
        config:
          prefix: "bce"
          uri: "http://host.docker.internal:3000/validate"
