_format_version: "2.1"
_transform: true

services:
  - url: http://echo
    routes:
      - paths:
          - "/jwt"
    plugins:
      - name: kong-jwt-plugin
        config:
          jwt:
            prefix: "bce"
            claims:
              - name: "uid"
          publickey: |
            -----BEGIN PUBLIC KEY-----
            MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwr1BKvAQRnXADBjMVucJ
            I9hKC4U4H3cQQokUHQRDCnuHZTMcsVdB9NR7ucnp1qsDt716+Drz3lheyQiZhyVg
            jqqQLi5kOTKzuTvNTzXytjxMBmPO0zI20XSAPQdTBmcRJL3z1OmhKEhmIz1g4A8K
            Uedyt4WbHo+IYIGQF8qGnxOQksT6SUnhi4gxW1qRcaZJMtB7dEJw4tEU05vdCLL9
            tXLKSNJtoEr3xXSmcJoGMTvp3SCkxccSSTkMInWXZ4WMSUXg5ZUNb94NBcJwdX1v
            n5fXbfQ1j3w+/OOxOoydRHTmHQ1Ux0Z4TYu5W2Hf+Jb0+UG1KD8BSbxNEIxwr3ZH
            ij3BBhfB0Oscw66hhjwwJR4EZXQ3SZb/UiPLbx8TgyOj4yru8tzoDzz8WUs7cadh
            zE4oubpfGatTVbWa08VB0eKzPQx5EYFN9okUYx/+6AIZJv38J5NHld663Sc+oUwl
            1r+faxcZhXg6kSW9zVUoR+MCAwEAAQ==
            -----END PUBLIC KEY-----

  - url: http://echo
    routes:
      - paths:
          - "/forward-auth"
    plugins:
      - name: kong-forward-auth-plugin
        config:
          prefix: "bce"
          uri: "http://host.docker.internal:3000/validate"
